<a href="https://colab.research.google.com/github/cindyyputri/python_training_series/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IFSI46 - Cindy Putri Az Zahra - 09031282126072**

**Python Training Series: Tensors**


## Exercises


1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [ ]:
import tensorflow as tf

scalar = tf.constant(42)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
print("Scalar Shape:", scalar.shape)
print("Scalar Rank:", tf.rank(scalar))
print("Scalar Size:", tf.size(scalar))

print("\nVector Shape:", vector.shape)
print("Vector Rank:", tf.rank(vector))
print("Vector Size:", tf.size(vector))

print("\nMatrix Shape:", matrix.shape)
print("Matrix Rank:", tf.rank(matrix))
print("Matrix Size:", tf.size(matrix))

print("\nTensor Shape:", tensor.shape)
print("Tensor Rank:", tf.rank(tensor))
print("Tensor Size:", tf.size(tensor))

Scalar Shape: ()
Scalar Rank: tf.Tensor(0, shape=(), dtype=int32)
Scalar Size: tf.Tensor(1, shape=(), dtype=int32)

Vector Shape: (5,)
Vector Rank: tf.Tensor(1, shape=(), dtype=int32)
Vector Size: tf.Tensor(5, shape=(), dtype=int32)

Matrix Shape: (3, 3)
Matrix Rank: tf.Tensor(2, shape=(), dtype=int32)
Matrix Size: tf.Tensor(9, shape=(), dtype=int32)

Tensor Shape: (2, 2, 3)
Tensor Rank: tf.Tensor(3, shape=(), dtype=int32)
Tensor Size: tf.Tensor(12, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [ ]:
tensor_a = tf.random.uniform([5, 300], minval=0, maxval=1)
tensor_b = tf.random.uniform([5, 300], minval=0, maxval=1)

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tensor_a_transposed = tf.transpose(tensor_a)
matrix_multiplication_result = tf.matmul(tensor_a_transposed, tensor_b)
print("\nMatrix Multiplication Result Shape:", matrix_multiplication_result.shape)


Matrix Multiplication Result Shape: (300, 300)


5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
dot_product_result = tf.reduce_sum(tf.multiply(tensor_a, tensor_b), axis=1)
print("\nDot Product Result Shape:", dot_product_result.shape)
print("Dot Product Result:", dot_product_result)


Dot Product Result Shape: (5,)
Dot Product Result: tf.Tensor([76.02815  76.800674 76.688156 74.01249  72.25003 ], shape=(5,), dtype=float32)


6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
random_tensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1)
print("\nRandom Tensor Shape:", random_tensor.shape)


Random Tensor Shape: (224, 224, 3)


7. Find the min and max values of the tensor you created in 6.

In [ ]:
min_val = tf.reduce_min(random_tensor)
max_val = tf.reduce_max(random_tensor)
print("\nMin Value in Random Tensor:", min_val.numpy())
print("Max Value in Random Tensor:", max_val.numpy())


Min Value in Random Tensor: 6.198883e-06
Max Value in Random Tensor: 0.99999785


8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [ ]:
random_tensor_squeezed = tf.random.uniform([1, 224, 224, 3], minval=0, maxval=1)
squeezed_tensor = tf.squeeze(random_tensor_squeezed)
print("\nSqueezed Tensor Shape:", squeezed_tensor.shape)


Squeezed Tensor Shape: (224, 224, 3)


9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
values_tensor = tf.constant([3, 5, 7, 2, 8, 10, 1, 6, 9, 4])
max_index = tf.argmax(values_tensor)
print("\nIndex with Maximum Value in Tensor:", max_index.numpy())


Index with Maximum Value in Tensor: 5


10. One-hot encode the tensor you created in 9.

In [ ]:
one_hot_encoded_tensor = tf.one_hot(values_tensor, depth=10)
print("\nOne-Hot Encoded Tensor:\n", one_hot_encoded_tensor)


One-Hot Encoded Tensor:
 tf.Tensor(
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
